title: XOXDSEC
tagline: "Cybersecurity • Write-ups • Study Progress"
description: >-
  Welcome to my cybersecurity blog — a space where I document my journey through the world of security research, threat hunting, DFIR, AppSec, and everything in between. 
  Here, you'll find technical articles, deep-dives, personal studies, and write-ups based on real-world scenarios, labs, and challenges. 
  My goal is to share knowledge, reinforce concepts, and contribute to the infosec community while improving my own skills along the way. 
  Whether you're a beginner or a seasoned professional, I hope you’ll find value in the content shared here.

url: "https://xoxdsec.github.io"
baseurl: ""

theme: jekyll-theme-midnight

lang: en
timezone: America/Sao_Paulo

author:
  name: XOXDSEC
  email: xoxobughunter@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
